export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const OPEN_PRODUCTS_MODAL = 'OPEN_PRODUCTS_MODAL';
export const CLOSE_PRODUCTS_MODAL = 'CLOSE_PRODUCTS_MODAL';

export const ADD_TO_CART = 'ADD_TO_CART';